export enum ExecutionType {
  INTERNAL = 'INTERNAL',
  EXTERNAL = 'EXTERNAL',
}

export enum CampaignStatus {
  DRAFT = 'DRAFT',
  ANNOUNCED = 'ANNOUNCED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELED = 'CANCELED',
  PENDING = 'PENDING',
  DELAYED = 'DELAYED',
}