export enum ConsentStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  DECLINED = 'DECLINED',
  COMPLETED = 'COMPLETED',
  REVOKED = 'REVOKED', //Đã thu hồi
  UNDER_OBSERVATION = 'UNDER_OPSERVATION', //Đang theo dõi
  ADVERSE_REACTION = 'ADVERSE_REACTION', //Phản ứng phụ
}
