export enum ConsentStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  DECLINED = 'DECLINED',
  COMPLETED = 'COMPLETED',
  REVOKED = 'REVOKED',
  UNDER_OBSERVATION = 'UNDER_OPSERVATION',
  ADVERSE_REACTION = 'ADVERSE_REACTION'

}